import type { MacroCategory, Category } from '../types'

// tabType controls which tab each MacroCategory appears in on CategoriesPage:
//   'expense' → Despesas tab
//   'income'  → Receitas tab
//   'both'    → both tabs
//   'none'    → hidden from tabs (legacy/internal only)

export const MACRO_CATEGORIES: MacroCategory[] = [
  // ─── RECEITAS ───────────────────────────────────────────────────────────────
  {
    id: 'mac_receita_op', name: 'Salário',
    classificationType: 'operational_income',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#16A34A', icon: 'wallet', sortOrder: 1,
    tabType: 'income', budgetClassification: 'none', group: 'personal',
    keywords: ['salário', 'férias', '13º', 'plr', 'bonificações do trabalho', 'sulamerica', 'pagamento salário'],
    isDefault: true,
  },
  {
    id: 'mac_receita_ev', name: 'Outras Receitas',
    classificationType: 'extraordinary_income',
    displayInResult: true, displayInCashflow: true, displayInBudget: false,
    color: '#65A30D', icon: 'coins', sortOrder: 2,
    tabType: 'income', budgetClassification: 'none', group: 'personal',
    keywords: ['receitas diversas não categorizadas'],
    isDefault: true,
  },
  {
    id: 'mac_invest_rec', name: 'Investimentos',
    classificationType: 'redemption',
    displayInResult: false, displayInCashflow: true, displayInBudget: false,
    color: '#0D9488', icon: 'trending-up', sortOrder: 3,
    tabType: 'income', budgetClassification: 'none', group: 'personal',
    keywords: ['rendimentos', 'dividendos', 'juros de aplicações'],
    isDefault: true,
  },
  {
    id: 'mac_neutra_rec', name: 'Neutra',
    classificationType: 'neutral',
    displayInResult: false, displayInCashflow: true, displayInBudget: false,
    color: '#9CA3AF', icon: 'refresh-cw', sortOrder: 4,
    tabType: 'income', budgetClassification: 'none', group: 'personal', isNeutral: true,
    keywords: ['recebimento de transferência', 'estorno', 'reembolso interno', 'crédito de pagamento de fatura'],
    isDefault: true,
  },

  // ─── DESPESAS ────────────────────────────────────────────────────────────────
  {
    id: 'mac_alimentacao', name: 'Alimentação',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#F97316', icon: 'utensils', sortOrder: 10,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['supermercado', 'delivery', 'lanches', 'mercado', 'ifood', 'rappi'],
    isDefault: true,
  },
  {
    id: 'mac_assinaturas', name: 'Assinaturas',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#F59E0B', icon: 'repeat', sortOrder: 11,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['netflix', 'amazon prime', 'streaming', 'mensalidades de apps'],
    isDefault: true,
  },
  {
    id: 'mac_casa', name: 'Casa',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#6366F1', icon: 'home', sortOrder: 12,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['aluguel', 'condomínio', 'iptu', 'manutenção', 'móveis', 'decoração', 'energia', 'água', 'gás'],
    isDefault: true,
  },
  {
    id: 'mac_compras', name: 'Compra',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#F43F5E', icon: 'shopping-bag', sortOrder: 13,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['roupas', 'eletrônicos', 'acessórios', 'presentes', 'compras online', 'mercado livre'],
    isDefault: true,
  },
  {
    id: 'mac_cuidados', name: 'Cuidados Pessoais',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#0D9488', icon: 'sparkles', sortOrder: 14,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['cabeleireiro', 'barbeiro', 'estética', 'cosméticos', 'massagem'],
    isDefault: true,
  },
  {
    id: 'mac_divida', name: 'Dívidas',
    classificationType: 'debt_cost',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#991B1B', icon: 'alert-triangle', sortOrder: 15,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['empréstimos', 'financiamentos', 'parcelas', 'juros', 'cartão de crédito atrasado'],
    isDefault: true,
  },
  {
    id: 'mac_doacoes', name: 'Doações',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#DC2626', icon: 'hand-heart', sortOrder: 16,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['dízimo', 'caridade', 'doação', 'igreja'],
    isDefault: true,
  },
  {
    id: 'mac_educacao', name: 'Educação',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#8B5CF6', icon: 'book-open', sortOrder: 17,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['cursos', 'faculdade', 'livros', 'materiais', 'escola dos filhos'],
    isDefault: true,
  },
  {
    id: 'mac_impostos', name: 'Impostos e Taxas',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#B45309', icon: 'receipt', sortOrder: 18,
    tabType: 'expense', budgetClassification: 'none', group: 'personal',
    keywords: ['imposto', 'taxa', 'tarifa', 'iof', 'darf', 'multa fiscal'],
    isDefault: true,
  },
  {
    id: 'mac_invest_desp', name: 'Investimentos',
    classificationType: 'investment',
    displayInResult: false, displayInCashflow: true, displayInBudget: false,
    color: '#0891B2', icon: 'piggy-bank', sortOrder: 19,
    tabType: 'none', budgetClassification: 'none', group: 'personal',
    keywords: ['aportes em investimentos', 'previdência', 'poupança'],
    isDefault: true,
  },
  {
    id: 'mac_lazer', name: 'Lazer',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#EC4899', icon: 'ticket', sortOrder: 20,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['cinema', 'shows', 'festas', 'hobbies', 'entretenimento'],
    isDefault: true,
  },
  {
    id: 'mac_neutra_desp', name: 'Neutra',
    classificationType: 'neutral',
    displayInResult: false, displayInCashflow: true, displayInBudget: false,
    color: '#9CA3AF', icon: 'refresh-cw', sortOrder: 21,
    tabType: 'expense', budgetClassification: 'none', group: 'personal', isNeutral: true,
    keywords: ['pagamento de fatura', 'transferência entre contas', 'movimentação interna', 'saque'],
    isDefault: true,
  },
  {
    id: 'mac_outros_desp', name: 'Outros',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#6B7280', icon: 'more-horizontal', sortOrder: 22,
    tabType: 'none', budgetClassification: 'none', group: 'personal',
    keywords: ['diversos', 'sem categoria', 'gastos diversos'],
    isDefault: true,
  },
  {
    id: 'mac_pets', name: 'Pets',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#A16207', icon: 'paw-print', sortOrder: 23,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['ração', 'veterinário', 'petshop', 'acessórios para animais'],
    isDefault: true,
  },
  {
    id: 'mac_presentes', name: 'Presentes',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#DB2777', icon: 'gift', sortOrder: 24,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['presentes para família', 'amigos', 'datas comemorativas'],
    isDefault: true,
  },
  {
    id: 'mac_prestadores', name: 'Prestadores de Serviços',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#7C3AED', icon: 'users', sortOrder: 25,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['serviços pessoais', 'prestadores', 'ajudantes'],
    isDefault: true,
  },
  {
    id: 'mac_saude', name: 'Saúde',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#10B981', icon: 'heart-pulse', sortOrder: 26,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['farmácia', 'médicos', 'plano de saúde', 'exames', 'academia'],
    isDefault: true,
  },
  {
    id: 'mac_seguros', name: 'Seguros',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#0891B2', icon: 'shield', sortOrder: 27,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['seguro', 'porto seguro', 'loovi', 'azul seguros'],
    isDefault: true,
  },
  {
    id: 'mac_servicos', name: 'Serviços',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#64748B', icon: 'wrench', sortOrder: 28,
    tabType: 'expense', budgetClassification: 'essential', group: 'personal',
    keywords: ['internet', 'telefone', 'serviços gerais', 'manutenções'],
    isDefault: true,
  },
  {
    id: 'mac_trabalho', name: 'Trabalho',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#475569', icon: 'briefcase', sortOrder: 29,
    tabType: 'none', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['despesas relacionadas ao trabalho', 'material de escritório'],
    isDefault: true,
  },
  {
    id: 'mac_transporte', name: 'Transporte',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#0EA5E9', icon: 'car', sortOrder: 30,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['combustível', 'uber', 'transporte público', 'estacionamento', 'manutenção do carro'],
    isDefault: true,
  },
  {
    id: 'mac_viagem', name: 'Viagem',
    classificationType: 'operational_expense',
    displayInResult: true, displayInCashflow: true, displayInBudget: true,
    color: '#0284C7', icon: 'plane', sortOrder: 31,
    tabType: 'expense', budgetClassification: 'non_essential', group: 'personal',
    keywords: ['passagens', 'hospedagem', 'passeios', 'turismo', 'alimentação viagem'],
    isDefault: true,
  },

  // ─── LEGACY (hidden from tabs, kept for backwards compat) ───────────────────
  {
    id: 'mac_movfin', name: 'Movimentação Financeira',
    classificationType: 'neutral',
    displayInResult: false, displayInCashflow: true, displayInBudget: false,
    color: '#9CA3AF', icon: 'refresh-cw', sortOrder: 99,
    tabType: 'none',
    isNeutral: true,
  },
]

// ─── CATEGORIES (= subcategorias in new UI) ──────────────────────────────────

export const CATEGORIES: Category[] = [
  // ── Salário (mac_receita_op) ────────────────────────────────────────────────
  {
    id: 'cat_salario', name: 'Salário',
    macroCategoryId: 'mac_receita_op', classificationType: 'operational_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['salário', 'pagamento salário', 'holerite', 'folha de pagamento'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_reembolso_sal', name: 'Reembolso',
    macroCategoryId: 'mac_receita_op', classificationType: 'operational_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['reembolso empresa', 'sulamerica reembolso', 'reembolso creche', 'reembolso estacionamento'],
    budgetClassification: 'none',
  },

  // ── Outras Receitas (mac_receita_ev) ────────────────────────────────────────
  {
    id: 'cat_outras_receitas', name: 'Outras Receitas',
    macroCategoryId: 'mac_receita_ev', classificationType: 'extraordinary_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['receitas diversas', 'renda extra'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_fit_eit', name: 'FIT - EIT6247',
    macroCategoryId: 'mac_receita_ev', classificationType: 'extraordinary_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['pagamento fit eit6247', 'fit eit'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_fit', name: 'FIT - FXS9F24',
    macroCategoryId: 'mac_receita_ev', classificationType: 'extraordinary_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['rocket', 'fit fxs9f24'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_renda_empresa', name: 'Renda da empresa',
    macroCategoryId: 'mac_receita_ev', classificationType: 'extraordinary_income',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['renda da empresa', 'retirada empresa', 'pró-labore'],
    budgetClassification: 'none',
  },

  // ── Investimentos Receita (mac_invest_rec) ──────────────────────────────────
  {
    id: 'cat_resgate', name: 'Resgate',
    macroCategoryId: 'mac_invest_rec', classificationType: 'redemption',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['resgate', 'retirada investimento'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_aporte_rec', name: 'Aporte',
    macroCategoryId: 'mac_invest_rec', classificationType: 'redemption',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['aporte de investimento'],
    budgetClassification: 'none',
  },

  // ── Neutra Receita (mac_neutra_rec) ─────────────────────────────────────────
  {
    id: 'cat_outras_neutras_rec', name: 'Outras Neutras',
    macroCategoryId: 'mac_neutra_rec', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['movimentações sem impacto'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_pag_fatura_rec', name: 'Pagamento de Fatura de Cartão',
    macroCategoryId: 'mac_neutra_rec', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['estorno no crédito', 'crédito de fatura', 'pagamento fatura cartão'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_reembolso_rec', name: 'Reembolso Recebido',
    macroCategoryId: 'mac_neutra_rec', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['reembolso', 'reembolso recebido', 'estorno recebido'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_transf_entrada', name: 'Transferência Entrada',
    macroCategoryId: 'mac_neutra_rec', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: true, sortOrder: 4, active: true,
    keywords: ['transferência entrada', 'pix recebido entre contas próprias'],
    budgetClassification: 'none',
  },

  // ── Alimentação (mac_alimentacao) ────────────────────────────────────────────
  {
    id: 'cat_alimentacao', name: 'Alimentação',
    macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['supermercado', 'mercado', 'hortifruti', 'atacadão', 'carrefour'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_acougue', name: 'Açougue',
    macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['carnes', 'açougue'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_padaria', name: 'Padaria / Delivery',
    macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['padaria', 'delivery', 'ifood', 'rappi', 'lanche'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_restaurantes', name: 'Restaurantes',
    macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['restaurante', 'almoço', 'jantar', 'comida'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_suplementos', name: 'Suplementos',
    macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 5, active: true,
    keywords: ['whey', 'suplementos', 'max titanium', 'growth'],
    budgetClassification: 'non_essential',
  },

  // ── Assinaturas (mac_assinaturas) ────────────────────────────────────────────
  {
    id: 'cat_apple_storage', name: 'Apple Storage',
    macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['apple', 'icloud', 'storage'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_brasil_paralelo', name: 'Brasil Paralelo',
    macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['brasil paralelo', 'brasil para'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_ia', name: 'IA / Produtividade',
    macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['openai', 'chatgpt', 'claude', 'cursor', 'copilot', 'notion', 'produtividade'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_spotify', name: 'Spotify',
    macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['spotify'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_youtube', name: 'Youtube',
    macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 5, active: true,
    keywords: ['youtube', 'google youtube', 'youtube premium'],
    budgetClassification: 'non_essential',
  },

  // ── Casa (mac_casa) ──────────────────────────────────────────────────────────
  {
    id: 'cat_contas', name: 'Contas de Consumo',
    macroCategoryId: 'mac_casa', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['energia', 'água', 'gás', 'sabesp', 'enel', 'conta de luz', 'conta de água'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_iptu', name: 'IPTU',
    macroCategoryId: 'mac_casa', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['iptu', 'prefeitura', 'da pm osasco'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_manutencao_casa', name: 'Manutenção',
    macroCategoryId: 'mac_casa', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['depósito', 'bade', 'depositorqui', 'reforma', 'manutenção'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_prestacao', name: 'Prestação',
    macroCategoryId: 'mac_casa', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['prestação', 'parcela casa', 'financiamento casa'],
    budgetClassification: 'essential',
  },

  // ── Compra (mac_compras) ─────────────────────────────────────────────────────
  {
    id: 'cat_compras', name: 'Compras',
    macroCategoryId: 'mac_compras', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['roupas', 'eletrônicos', 'acessórios'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_ml', name: 'Mercado Livre / Amazon',
    macroCategoryId: 'mac_compras', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['amazon', 'mercado livre', 'mercadolivre'],
    budgetClassification: 'non_essential',
  },

  // ── Dívidas (mac_divida) ─────────────────────────────────────────────────────
  {
    id: 'cat_dividas', name: 'Dívidas',
    macroCategoryId: 'mac_divida', classificationType: 'debt_cost',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['empréstimo', 'financiamento', 'parcela'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_juros_cheque', name: 'Juros de Cheque Especial',
    macroCategoryId: 'mac_divida', classificationType: 'debt_cost',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['juros cheque especial', 'juros limite da conta', 'juros limite', 'cheque especial'],
    budgetClassification: 'essential',
  },

  // ── Educação (mac_educacao) ──────────────────────────────────────────────────
  {
    id: 'cat_bethel', name: 'Bethel',
    macroCategoryId: 'mac_educacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['bethel', 'escola bethel'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_idiomas', name: 'Idiomas',
    macroCategoryId: 'mac_educacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['inglês', 'idioma', 'aggile english', 'open english', 'cultura inglesa'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_jovens_negocios', name: 'Jovens de Negócios',
    macroCategoryId: 'mac_educacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['jovens de negócios'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_supera', name: 'Supera',
    macroCategoryId: 'mac_educacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['supera', 'osasco neuroeducacao', 'neuroeducacao'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_treinamentos', name: 'Treinamentos',
    macroCategoryId: 'mac_educacao', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 5, active: true,
    keywords: ['treinamento', 'curso', 'mentoria', 'formação'],
    budgetClassification: 'non_essential',
  },

  // ── Investimentos Despesa (mac_invest_desp) ──────────────────────────────────
  {
    id: 'cat_aporte', name: 'Aporte',
    macroCategoryId: 'mac_invest_desp', classificationType: 'investment',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['aporte', 'investimento', 'aplicação'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_resgate_desp', name: 'Resgate',
    macroCategoryId: 'mac_invest_desp', classificationType: 'investment',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['resgate', 'retirada investimento'],
    budgetClassification: 'none',
  },

  // ── Neutra Despesa (mac_neutra_desp) ─────────────────────────────────────────
  {
    id: 'cat_despesa_reemb', name: 'Despesa Reembolsável',
    macroCategoryId: 'mac_neutra_desp', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['reembolsável', 'reembolso futuro', 'despesa reembolsavel'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_outras_neutras_desp', name: 'Outras Neutras',
    macroCategoryId: 'mac_neutra_desp', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['movimentação sem impacto', 'ajuste interno'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_pag_cartao', name: 'Pagamento de Cartão',
    macroCategoryId: 'mac_neutra_desp', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['pagamento de cartão', 'pagamento fatura', 'fatura cartão'],
    budgetClassification: 'none',
  },
  {
    id: 'cat_transf_saida', name: 'Transferência Saída',
    macroCategoryId: 'mac_neutra_desp', classificationType: 'neutral',
    defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false,
    isInternalTransferDefault: true, sortOrder: 4, active: true,
    keywords: ['pix entre contas', 'ted entre contas', 'transferência saída', 'transferencia saida'],
    budgetClassification: 'none',
  },

  // ── Prestadores de Serviços (mac_prestadores) ────────────────────────────────
  {
    id: 'cat_baba', name: 'Babá',
    macroCategoryId: 'mac_prestadores', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['babá', 'baba', 'cuidadora', 'criança'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_faxina', name: 'Faxina',
    macroCategoryId: 'mac_prestadores', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['faxina', 'diarista', 'limpeza casa'],
    budgetClassification: 'non_essential',
  },

  // ── Saúde (mac_saude) ────────────────────────────────────────────────────────
  {
    id: 'cat_academias', name: 'Academias',
    macroCategoryId: 'mac_saude', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['academia', 'gympass', 'wellhub', 'acm'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_farmacia', name: 'Farmácia',
    macroCategoryId: 'mac_saude', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['farmácia', 'drogaria', 'drogasil', 'raia', 'drogaraia', 'drogaria são paulo'],
    budgetClassification: 'essential',
  },

  // ── Seguros (mac_seguros) ────────────────────────────────────────────────────
  {
    id: 'cat_seguro_azul', name: 'Azul - Fit FXS9F24',
    macroCategoryId: 'mac_seguros', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['azul', 'fit fxs9f24', 'seguro auto fit'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_loovi', name: 'Loovi',
    macroCategoryId: 'mac_seguros', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['loovi'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_porto_casa', name: 'Porto Casa',
    macroCategoryId: 'mac_seguros', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['porto casa', 'porto seguro casa'],
    budgetClassification: 'essential',
  },

  // ── Serviços (mac_servicos) ──────────────────────────────────────────────────
  {
    id: 'cat_claro_tv', name: 'Claro TV',
    macroCategoryId: 'mac_servicos', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['claro tv', 'claro', 'net', 'claro residencial'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_mensalidades', name: 'Mensalidades',
    macroCategoryId: 'mac_servicos', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['mensalidade', 'assinatura serviço', 'recorrente serviço'],
    budgetClassification: 'essential',
  },
  {
    id: 'cat_vivo', name: 'VIVO',
    macroCategoryId: 'mac_servicos', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['vivo', 'telefone', 'internet vivo'],
    budgetClassification: 'essential',
  },

  // ── Transporte (mac_transporte) ──────────────────────────────────────────────
  {
    id: 'cat_acessorios_auto', name: 'Acessórios',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 1, active: true,
    keywords: ['acessório carro', 'acessórios', 'autopeças'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_combustivel', name: 'Combustível',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 2, active: true,
    keywords: ['posto', 'combustível', 'gasolina', 'etanol', 'petrobras', 'shell', 'ipiranga'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_estacionamento', name: 'Estacionamento / Sem Parar',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 3, active: true,
    keywords: ['sem parar', 'estacionamento', 'pedágio', 'pedagio'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_limpeza_auto', name: 'Limpeza',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 4, active: true,
    keywords: ['lava rápido', 'lavagem', 'limpeza carro'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_manutencao_auto', name: 'Manutenção',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 5, active: true,
    keywords: ['oficina', 'manutenção carro', 'mecânico', 'auto center'],
    budgetClassification: 'non_essential',
  },
  {
    id: 'cat_multas_auto', name: 'Multas e Taxas',
    macroCategoryId: 'mac_transporte', classificationType: 'operational_expense',
    defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true,
    isInternalTransferDefault: false, sortOrder: 6, active: true,
    keywords: ['multa', 'detran', 'licenciamento', 'ipva'],
    budgetClassification: 'none',
  },
]

export const getMacroById = (id: string): MacroCategory | undefined =>
  MACRO_CATEGORIES.find(m => m.id === id)

export const getCategoryById = (id: string): Category | undefined =>
  CATEGORIES.find(c => c.id === id)
