import type { MacroCategory, Category } from '../types'

export const MACRO_CATEGORIES: MacroCategory[] = [
  { id: 'mac_receita_op', name: 'Receitas Operacionais', classificationType: 'operational_income', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#16A34A', icon: 'trending-up', sortOrder: 1 },
  { id: 'mac_receita_ev', name: 'Receitas Eventuais', classificationType: 'extraordinary_income', displayInResult: true, displayInCashflow: true, displayInBudget: false, color: '#65A30D', icon: 'coins', sortOrder: 2 },
  { id: 'mac_alimentacao', name: 'Alimentação', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#F97316', icon: 'utensils', sortOrder: 3 },
  { id: 'mac_casa', name: 'Casa', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#6366F1', icon: 'home', sortOrder: 4 },
  { id: 'mac_saude', name: 'Saúde', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#10B981', icon: 'heart-pulse', sortOrder: 5 },
  { id: 'mac_transporte', name: 'Transporte', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#0EA5E9', icon: 'car', sortOrder: 6 },
  { id: 'mac_educacao', name: 'Educação', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#8B5CF6', icon: 'book-open', sortOrder: 7 },
  { id: 'mac_assinaturas', name: 'Assinaturas', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#F59E0B', icon: 'repeat', sortOrder: 8 },
  { id: 'mac_compras', name: 'Compras', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#F43F5E', icon: 'shopping-bag', sortOrder: 9 },
  { id: 'mac_servicos', name: 'Serviços', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#64748B', icon: 'wrench', sortOrder: 10 },
  { id: 'mac_seguros', name: 'Seguros', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#0891B2', icon: 'shield', sortOrder: 11 },
  { id: 'mac_lazer', name: 'Lazer', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#EC4899', icon: 'ticket', sortOrder: 12 },
  { id: 'mac_pets', name: 'Pets', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#A16207', icon: 'paw-print', sortOrder: 13 },
  { id: 'mac_presentes', name: 'Presentes', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#DB2777', icon: 'gift', sortOrder: 14 },
  { id: 'mac_doacoes', name: 'Doações', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#DC2626', icon: 'hand-heart', sortOrder: 15 },
  { id: 'mac_prestadores', name: 'Prestadores', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#7C3AED', icon: 'users', sortOrder: 16 },
  { id: 'mac_impostos', name: 'Impostos e Taxas', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#B45309', icon: 'receipt', sortOrder: 17 },
  { id: 'mac_cuidados', name: 'Cuidados Pessoais', classificationType: 'operational_expense', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#0D9488', icon: 'sparkles', sortOrder: 18 },
  { id: 'mac_divida', name: 'Dívida', classificationType: 'debt_cost', displayInResult: true, displayInCashflow: true, displayInBudget: true, color: '#991B1B', icon: 'alert-triangle', sortOrder: 19 },
  { id: 'mac_movfin', name: 'Movimentação Financeira', classificationType: 'neutral', displayInResult: false, displayInCashflow: true, displayInBudget: false, color: '#9CA3AF', icon: 'refresh-cw', sortOrder: 20 },
]

export const CATEGORIES: Category[] = [
  { id: 'cat_salario', name: 'Salário', macroCategoryId: 'mac_receita_op', classificationType: 'operational_income', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_fit', name: 'Pagamento FIT', macroCategoryId: 'mac_receita_op', classificationType: 'operational_income', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_outras_receitas', name: 'Outras Receitas', macroCategoryId: 'mac_receita_ev', classificationType: 'extraordinary_income', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: false, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_alimentacao', name: 'Alimentação', macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_restaurantes', name: 'Restaurantes', macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_padaria', name: 'Padaria / Delivery', macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 3, active: true },
  { id: 'cat_acougue', name: 'Açougue', macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 4, active: true },
  { id: 'cat_suplementos', name: 'Suplementos', macroCategoryId: 'mac_alimentacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 5, active: true },
  { id: 'cat_prestacao', name: 'Prestação', macroCategoryId: 'mac_casa', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_contas', name: 'Contas de Consumo', macroCategoryId: 'mac_casa', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_iptu', name: 'IPTU', macroCategoryId: 'mac_casa', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 3, active: true },
  { id: 'cat_manutencao_casa', name: 'Manutenção', macroCategoryId: 'mac_casa', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 4, active: true },
  { id: 'cat_academias', name: 'Academias', macroCategoryId: 'mac_saude', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_farmacia', name: 'Farmácia', macroCategoryId: 'mac_saude', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_combustivel', name: 'Combustível', macroCategoryId: 'mac_transporte', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_estacionamento', name: 'Estacionamento / Sem Parar', macroCategoryId: 'mac_transporte', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_bethel', name: 'Bethel', macroCategoryId: 'mac_educacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_idiomas', name: 'Idiomas', macroCategoryId: 'mac_educacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_supera', name: 'Supera', macroCategoryId: 'mac_educacao', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 3, active: true },
  { id: 'cat_ia', name: 'IA / Produtividade', macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_spotify', name: 'Spotify', macroCategoryId: 'mac_assinaturas', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_compras', name: 'Compras', macroCategoryId: 'mac_compras', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_ml', name: 'Mercado Livre / Amazon', macroCategoryId: 'mac_compras', classificationType: 'operational_expense', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 2, active: true },
  { id: 'cat_dividas', name: 'Dívidas', macroCategoryId: 'mac_divida', classificationType: 'debt_cost', defaultIncludeInOperationalResult: true, defaultIncludeInCashflow: true, defaultIncludeInBudget: true, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_resgate', name: 'Resgate', macroCategoryId: 'mac_movfin', classificationType: 'redemption', defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false, isInternalTransferDefault: false, sortOrder: 1, active: true },
  { id: 'cat_aporte', name: 'Aporte', macroCategoryId: 'mac_movfin', classificationType: 'investment', defaultIncludeInOperationalResult: false, defaultIncludeInCashflow: true, defaultIncludeInBudget: false, isInternalTransferDefault: false, sortOrder: 2, active: true },
]

export const getMacroById = (id: string): MacroCategory | undefined =>
  MACRO_CATEGORIES.find(m => m.id === id)

export const getCategoryById = (id: string): Category | undefined =>
  CATEGORIES.find(c => c.id === id)
